### ISSUE TITLE
Haddock failure on master with GHC 8.4

### ISSUE THREAD

**Issue by sjakobi** [sdiehl/repline#31]
```
$ cabal haddock -w ghc-8.4.4
...
src/System/Console/Repline.hs:247:3: error:
    parse error on input ‘-- | banner function’
    |
247 |   -- | banner function
    |   ^^^^^^^^^^^^^^^^^^^^
```

@basile-henry mentioned this in https://github.com/dhall-lang/dhall-haskell/pull/1867/files#r441794458.

I'd recommend checking haddock-compatibility in CI BTW.

**Comment by sdiehl** [comment]
Fixed in 7bcff62

**Comment by basile-henry** [comment]
This issue is back in the release! I think it's a problem with the way Ormolu formats function types which is incompatible with GHC 8.4 haddock parser. :cry:

**Comment by sdiehl** [comment]
Like they say in the ormolu thread, it builds fine on recent versions of GHC so this seems low priority. If you want to submit a patch for the Haddock I'd be happy to merge it, if it's compatible with every Haddock parser.

**Comment by adamwespiser** [comment]
This is coming up, again, when we try to build the documentation for this project using ghc 8.2 and 8.4.
I don't think it's worth updating haddock for those versions, and my tendency is to drop official support for ghc 8.2/8.4 for repline.

**Comment by sjakobi** [comment]
Sounds good to me! :+1:
